spring:
  application:
    name: HospitalManagementSystem

  datasource:
    url: "jdbc:mysql://localhost:3306/hospital_db"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
