spring:
  application:
    name: HospitalManagementSystem

  datasource:
    url: "jdbc:mysql://localhost:3306/hospital_db"
    username: root
    password: Shwetha@29

  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: "sandbox.smtp.mailtrap.io"
    port:  25
    username: 9bd505c7416268
    password: ea4ebd810a14dc



security:
    jwt:
      secret: ${JWT_SECRET:verysecretkeyverysecretkeyverysecretkey}
      expiration: ${JWT_EXPIRY:900000}

refresh:
  token:
    expiration: ${REFRESHTOKEN_EXPIRY:604800000}