spring:
  application:
    name: HospitalManagementSystem

  datasource:
    url: "jdbc:mysql://localhost:3306/hospital_db"
    username: root
    password: Shwetha@29

  jpa:
    hibernate:
      ddl-auto: create


  security:
    jwt:
      secret: ${JWT_SECRET:verysecretkeyverysecretkeyverysecretkey}
